INITIAL_ENEMIES_NUMBER = 1

MSG_NEW_PLAYER = "NEW_PLAYER_REQUEST"
MSG_START_GAME = "START_GAME_REQUEST"
MSG_PLAYER_POSITION_CHANGED = "PLAYER_POSITION_CHANGED"
MSG_REMOVE_ENEMY = "REMOVE_ENEMY_REQUEST"