INITIAL_ENEMIES_NUMBER = 1

START_GAME_REQUEST = "START_GAME_REQUEST"
NEW_PLAYER_REQUEST = "NEW_PLAYER_REQUEST"
PLAYER_POSITION_CHANGED = "PLAYER_POSITION_CHANGED"
REMOVE_ENEMY_REQUEST = "REMOVE_ENEMY_REQUEST"